matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - config/spellcheck/wordlist.txt
    - config/spellcheck/wordlist-orgs-authors.txt
    output: config/spellcheck/wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:
      # - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: true
      # attributes:
      # - title
      # - alt
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'
  sources:
  - 'patterns/2-structured/**/*.md'
  default_encoding: utf-8
